export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import type { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
