/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AdyenConfig, CreditCardFormData } from "./modules/credit-card-form/credit-card-form";
import { CardPlaceholders } from "@adyen/adyen-web";
import { ButtonSize, ButtonVariant } from "./components/my-button/my-button";
export { AdyenConfig, CreditCardFormData } from "./modules/credit-card-form/credit-card-form";
export { CardPlaceholders } from "@adyen/adyen-web";
export { ButtonSize, ButtonVariant } from "./components/my-button/my-button";
export namespace Components {
    interface CreditCardForm {
        "adyenConfig": AdyenConfig;
        "cardStyles"?: StylesObject;
        /**
          * @default false
         */
        "disabled": boolean;
        "placeholder"?: CardPlaceholders;
    }
    interface MyButton {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default "md"
         */
        "size": ButtonSize;
        /**
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * @default "primary"
         */
        "variant": ButtonVariant;
    }
}
export interface CreditCardFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCreditCardFormElement;
}
export interface MyButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyButtonElement;
}
declare global {
    interface HTMLCreditCardFormElementEventMap {
        "formReady": void;
        "formChange": CreditCardFormData;
        "formSubmit": CreditCardFormData;
        "formError": { message: string; error: unknown };
    }
    interface HTMLCreditCardFormElement extends Components.CreditCardForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCreditCardFormElementEventMap>(type: K, listener: (this: HTMLCreditCardFormElement, ev: CreditCardFormCustomEvent<HTMLCreditCardFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCreditCardFormElementEventMap>(type: K, listener: (this: HTMLCreditCardFormElement, ev: CreditCardFormCustomEvent<HTMLCreditCardFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCreditCardFormElement: {
        prototype: HTMLCreditCardFormElement;
        new (): HTMLCreditCardFormElement;
    };
    interface HTMLMyButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyButtonElementEventMap>(type: K, listener: (this: HTMLMyButtonElement, ev: MyButtonCustomEvent<HTMLMyButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyButtonElementEventMap>(type: K, listener: (this: HTMLMyButtonElement, ev: MyButtonCustomEvent<HTMLMyButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLElementTagNameMap {
        "credit-card-form": HTMLCreditCardFormElement;
        "my-button": HTMLMyButtonElement;
    }
}
declare namespace LocalJSX {
    interface CreditCardForm {
        "adyenConfig": AdyenConfig;
        "cardStyles"?: StylesObject;
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onFormChange"?: (event: CreditCardFormCustomEvent<CreditCardFormData>) => void;
        "onFormError"?: (event: CreditCardFormCustomEvent<{ message: string; error: unknown }>) => void;
        "onFormReady"?: (event: CreditCardFormCustomEvent<void>) => void;
        "onFormSubmit"?: (event: CreditCardFormCustomEvent<CreditCardFormData>) => void;
        "placeholder"?: CardPlaceholders;
    }
    interface MyButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onButtonClick"?: (event: MyButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default "md"
         */
        "size"?: ButtonSize;
        /**
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * @default "primary"
         */
        "variant"?: ButtonVariant;
    }

    interface CreditCardFormAttributes {
        "disabled": boolean;
    }
    interface MyButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "disabled": boolean;
        "type": "button" | "submit" | "reset";
    }

    interface IntrinsicElements {
        "credit-card-form": Omit<CreditCardForm, keyof CreditCardFormAttributes> & { [K in keyof CreditCardForm & keyof CreditCardFormAttributes]?: CreditCardForm[K] } & { [K in keyof CreditCardForm & keyof CreditCardFormAttributes as `attr:${K}`]?: CreditCardFormAttributes[K] } & { [K in keyof CreditCardForm & keyof CreditCardFormAttributes as `prop:${K}`]?: CreditCardForm[K] };
        "my-button": Omit<MyButton, keyof MyButtonAttributes> & { [K in keyof MyButton & keyof MyButtonAttributes]?: MyButton[K] } & { [K in keyof MyButton & keyof MyButtonAttributes as `attr:${K}`]?: MyButtonAttributes[K] } & { [K in keyof MyButton & keyof MyButtonAttributes as `prop:${K}`]?: MyButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "credit-card-form": LocalJSX.IntrinsicElements["credit-card-form"] & JSXBase.HTMLAttributes<HTMLCreditCardFormElement>;
            "my-button": LocalJSX.IntrinsicElements["my-button"] & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
        }
    }
}
